repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-json
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.50.0
    hooks:
    -   id: golangci-lint
