version: "3"

services:
  go-savings-bot:
    container_name: go_savings_bot
    image: go_savings_bot
    build: .
    environment:
    - BOT_TOKEN=<token>

    restart: unless-stopped
    volumes:
      - "./data:/app/data"

